(example) ♻️ refac: Switch to singleton pattern in app_env.dart
petercinibulk/envied pull request #110
Opened 2024-08-17 07:17 UTC by flawnn

Hey 👋

Little change that, I thought, is quite nice, especially regarding people who copy the example & use it straightaway.
 
The reasoning is that it is plain better, & more efficent to implement the Singleton pattern with the Dart Factories for the `AppEnv` than to create a new instance with each call to the constructor

2024-08-18 08:19 UTC, techouse approved these changes

2024-08-18 08:19 UTC, techouse requested changes
Please fix the linter errors

2024-08-18 11:30 UTC, flawnn commented
Is done! Sorry, something went wrong on my side there.

2024-08-19 22:35 UTC, techouse requested changes
Looks like there are still some formatting/styling issues.

2024-10-03 23:54 UTC, indiealchemy commented
How's this going ?

2024-11-04 14:27 UTC, ThexXTURBOXx commented
Does this really make any difference? As far as I can see, there is always only a single instance that is being created since the field was always marked `static final`.
The "constructor" (i.e., factory) just returns this instance that was created at some point - basically the same procedure as a singleton, just easier to read, less to write and exactly as efficient.
Because of this, I actually prefer the old code.

2024-11-06 22:23 UTC, techouse commented
> As far as I can see, there is always only a single instance that is being created since the field was always marked `static final`.

Fair point.

2024-11-06 22:23 UTC, closed without merging