chore: coverage:ignore-file
petercinibulk/envied pull request #43
Opened 2023-07-26 08:00 UTC by anggaaryas

// coverage:ignore-file

usage: ignore generated file from being coverage by flutter

2023-08-07 19:27 UTC, petercinibulk requested changes
Please update the tests so they contain this newly added line

2023-09-02 08:33 UTC, techouse commented
This can be integrated easily once #57 lands

2023-09-22 19:47 UTC, petercinibulk approved these changes

2023-09-25 23:43 UTC, techouse commented
Superseded in #63

2023-09-25 23:43 UTC, closed without merging